# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wLc6yOC7Qvr7El4K9UI10nGZrX_-ld00
"""

n=int(input("enter the number"))
if (n==0):
  print("monday")
elif(n==1):
  print("tuesday")
elif(n==2):
  print("wednesday")
elif(n==3):
  print("thursday")
elif(n==4):
  print("friday")
elif(n==5):
  print("saturday")
elif(n==6):
  print("sunday")
else:
    print("invalid")

s=10
for i in range(10):
  for j in range(i+1):
    print("*",end="")
  print("\n")

for i in range(5):
  start=65
  for j in range(i+1):
    print(chr(start),end="")
    start=start+1
  print("\n")

l=int(input("enter the limit"))
for i in range(l):
  n=1
  for j in range(i+1):
    print(n,'\t',end="")
    n=n+1
  print("\n")

for row in range(6):
  for col in range(7):
    if(row==0 and col%3!=0)or(row==1 and col%3==0) or (row-col==2) or (row+col==8):
      print("*",end='')
    else:
       print(end='')
  print()

n=6
for row in range(0,n):
  for col in range(0,n+1):
    if(row==0 and col%3!=0)or(row==1 and col%3==0) or (row-col==2) or (row+col==8):
      print("*",end='')
    else:
       print("",end='')
  print()

n=6
for r in range(0,n):
    for c in range(0,n+1):
        if(r==0 and c%3!=0) or (r==1 and c%3==0) or (r-c==2) or(r+c==8):
          print('*',end='    ')
        elif(r==2 and c==1):
          print("E",end="   ") 
        elif(r==2 and c==2):
          print("E",end="   ") 
        elif(r==2 and c==3):
          print("M",end="   ")  
        elif(r==2 and c==4):
          print("A",end="   ")
        elif(r==2 and c==5):
          print("N",end="   ")                 
        else:
            print('',end="    ")
    print()