# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nLMEjcAAZAzGOUILqaDfZrG4LsFfRENc
"""

a=[1,2,3,4,5,6,7,8,9]
b=['a','b','c','d']
print(a)
print(b)
print(len(a))
print(len(b))

print(a[0:5])
print(b[1:3])



a[8]=10
print(a)

print(type(a))

a.append(11)
print(a)

a.pop()
print(a)

c=a.copy()
print(c)

d=a.sort()
print(d)

e=a+b
print(e)

c=('a','b','c','d')
e=(3,4,5,6,7,8)
print(c)
print(e)
print(len(c))
print(type(e))
print(c[0:3])
g=list(c)

s={'year':'2017','engine_no':'52WVC10338','model':'BMW'}
v={'year':'2014','engine_no':'52WVC10366','model':'Benz'}
print(s)
print(v)
print(len(s))
print(type(v))
print(v['model'])
v['model']='ford'
print(v)
v.pop(['model'])