# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N0f4OwmUEgnvvpfr6kKex2x9-o_hQqUs
"""

name="eeman"
print (name)
print(name[3:])

a=10
print(type(a))
b=str(a)
print(type(b))

str1="hello world"
print(str1)
for i in str1:
     print(i)

print("e" in str1)
print("a" in str1)

n=0
while(n<10):
  n=n+1
  print(n)

n=10
for i in range(1,10):
  print(i)

for i in range(10,0,-1):
  print(i)