# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/146jj1OgkO2iSvMtu99iCSNDTkJThSsCa
"""

a=int(input("enter the number"))
b=int(input("enter the number"))
class calc:
  def __init__(self,a,b):
    self.a=a
    self.b=b
  def add(self):
    r=self.a+self.b
    return r  
  def sub(self):
    r=self.a-self.b
    return r 
  def mul(self):
    r=self.a*self.b
    return r
  def div(self):
    r=self.a/self.b
    return r

c=calc(a,b)
c.add()

c.sub()

c.mul()

c.div()